trigger:
  branches:
    include:
      - main

variables:
  acrServiceConnection: 'pythoncr-connection'
  azureSubscription: 'rg-python-connection'
  imageRepository: 'studenthub'
  containerRegistry: 'pythoncr.azurecr.io'
  aksResourceGroup: 'rg-python'
  aksClusterName: 'aks-python'
  imageTag: '$(Build.BuildId)'

stages:

- stage: Build
  displayName: Build & Push Image

  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(imageTag)
          latest

    - task: PublishPipelineArtifact@1
      displayName: Publish Kubernetes Manifests
      inputs:
        targetPath: '$(Build.SourcesDirectory)/k8s'
        artifact: 'k8s-manifests'

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: production

    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadPipelineArtifact@2
            displayName: Download Kubernetes Manifests
            inputs:
              artifact: 'k8s-manifests'
              path: '$(Pipeline.Workspace)/k8s'

          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              connectionType: azureResourceManager
              azureSubscriptionConnection: '$(azureSubscription)'
              azureResourceGroup: '$(aksResourceGroup)'
              kubernetesCluster: '$(aksClusterName)'
              namespace: default
              manifests: |
                $(Pipeline.Workspace)/k8s/postgres-secret.yaml
                $(Pipeline.Workspace)/k8s/postgres.yaml
                $(Pipeline.Workspace)/k8s/deployment.yaml
                $(Pipeline.Workspace)/k8s/service.yaml
              containers: |
                $(containerRegistry)/$(imageRepository):$(imageTag)